package dominion;

/**
 * Created by Flo on 06/12/2016.
 */
public enum EtapesTour {
    ACTION,
    ACHAT,
    CHOIX_1_CARTE_DE_MAIN,
    CHOIX_1_CARTE_TRESOR_DE_MAIN,
    CHOIX_1_CARTE_ACTION_DE_MAIN,
    CHOIX_JUSQUA_4_CARTES_DE_MAIN,
    DEFAUSSER_AUTANT_CARTES_MAIN_QUON_VEUT,

    TOUS_ADVERSAIRES_DEFAUSSENT_POUR_PLUS_QUE_3_CARTES_EN_MAIN,
    TOUS_ADVERSAIRES_CHOIX_CARTE_VICTOIRE_DANS_MAIN,

    TOUS_ADVERSAIRES_DEVOILENT_2_PREMIERES_CARTES_DECK,
    TOUS_ADVERSAIRES_DEVOILENT_1ERE_CARTE_DECK
}
